### ISSUE TITLE
Demultiplex feedback - Perris N

### ISSUE THREAD

**Issue by perrisn** [aw-watson/Demultiplex#2]
Great job André! I just had a few comments:

- It might be a good idea to somehow open files to write as you go (number 2 of process) instead of all at once in case anything is missing 
- How do you plan to store the reverse complement of second index before you replace the second read sequence with it? (number 4 of process)?
- How do you plan to calculate average quality score? 
- This comment is more for the ease of the person reading the pseudocode, but adding where you initialize each dictionary, list, etc. helps me keep track of all the data types :) 

I really liked how nicely organized your train of thought was!

**Comment by aw-watson** [comment]
Thanks for the feedback!

I think it'll be more clear to have the file connections for output files open at the top; I want to avoid confusing conditionals in the loop. That does mean a cleanup phase will be needed, though, see #6.

The original sequence of the second index is stored in the list where we keep a record from R3 (at index 2). We can just replace it with its own reverse complement, no need to keep an intermediary. That makes comparing index pairs easier, and since the only thing we're keeping from the index reads in our output is an annotation in the header lines for the main reads, it's fine to manipulate the records from the index reads.

I'll add a function definition for calculating average quality scores. See #5.

Specifying where data structures are initialized will be helpful, see #4.

**Comment by aw-watson** [comment]
All issues resolved!
